### ISSUE TITLE
[Help] - Regarding "Reached maximum allowed buffered messages for this connection." error

### ISSUE THREAD

**Issue by Ddreig** [coinapi/coinapi-sdk#102]
Hello, would like to bring up this issue where the error maximum allowed buffered messages is received.

For our procedure, we are purely enqueueing (using ConcurrentQueue) the data received from websocket under Trade message and still receiving the mentioned error.

![image](https://user-images.githubusercontent.com/55972719/117031469-32136000-ad33-11eb-81de-6614a3a36909.png)

It should also be noted that we are not doing any processing and just purely receiving data. Also when using ConcurrentQueue, it can process 1 million data in around 20 milliseconds, so it shouldn't cause a bottleneck when processing data received.

For the datacenter, we are using Azure VM and that the network bandwidth is very high and is located in Singapore Region.

Edit: Additional Question: What does the error "The operation was canceled." mean when it is received?

**Comment by Svisstack** [comment]
@Ddreig Are you still experiencing this problem? What is the instance type and CPU load on it?
