### ISSUE TITLE
API returns empty list for HUOBI_SPOT_ETH_USDT

### ISSUE THREAD

**Issue by liweidong1218** [coinapi/coinapi-sdk#103]
I am not able to pull any result using the symbol 'HUOBI_SPOT_ETH_USDT'. However, 'HUOBIPRO_SPOT_ETH_USDT' works fine. I'm wondering why is that. Could anyone look into this? Many thanks!

**Comment by Svisstack** [comment]
HUOBI and HUOBIPRO are different exchanges and therefore have different data availability. 

If you need more information please contact support as this is not related to the SDK.
