### ISSUE TITLE
New R package for REST API

### ISSUE THREAD

**Issue by Ramshreyas** [coinapi/coinapi-sdk#107]
Hi Guys,

I've put together an R package for the REST API - https://github.com/Ramshreyas/rcoinapi

The aim is to mimic Quantmod response objects (basically the OHLCV data), so that existing functionality can be brought to bear with minimum effort.

Feedback most welcome!

**Comment by Svisstack** [comment]
@Ramshreyas Great job! 

Can you just make PR to this repo as we will have it in ./data-api/r-rest-2 directory and other people can participate in developing that alongside?

**Comment by Ramshreyas** [comment]
@Svisstack sure, I'll do that but to be honest it won't be very useful to R coders.

The way R works developers working with github packages (as opposed to the official CRAN repos) do this:

install_github("Ramshreyas/rcoinapi")

With just the "name of the user/name of repo" as the argument.

You will be better off forking my repo, so that they can do:

install_github("coinapi/r") 

or whatever name you prefer. Then PRs can go directly to that repo and usage, testing etc will work work of the box.

Plus, the way the auto-generated documentation (which I've also created) namespace etc works, it's better if it is at the root of the repo and therefore easy for others to work with. 

If the code is buried in your SDKs repo, there are a couple of steps before R programmers can get started working with the package immediately, and they will have to do it each time they want to make a change.

Let me know how you would like to proceed! 

Also, I'm putting together a tutorial which shows the API working within a typical R backtesting workflow, which I'll post here once it's ready.

**Comment by Ramshreyas** [comment]
@Svisstack : as promised, here is a complete tutorial using RCoinAPI (or whatever you want to call it in the future) to get Crypto data and perform a backtest using Quantstrat, the industry standard for backtesting in R:

https://philosophyofquant.com/post/2021-07-05-rcoinapi/

Please let me know if you prefer a PR to your existing repo (which I'd advise against) or would you like to just fork my repo, and we can proceed and close accordingly.

Cheers!

**Comment by Ramshreyas** [comment]
@Svisstack I'm assuming you prefer the code under ./data-api/r-rest-2 as opposed to a new repo - have made the PR accordingly.

**Comment by Svisstack** [comment]
Hi, @Ramshreyas Thanks for making that happen in the subdirectory fashion as it reflects our current SDK structure where there multiple languages in the separate subdirectories instead of separate repositories.

Can you also advise if that import line is correct after the merge?

https://github.com/coinapi/coinapi-sdk/commit/0b8aa4759ada850f182d047b4a4683427af1fb7c#diff-727b26c4933a46e039d64e662a92c107252bbd9b4579dfc2fe97f6824af8cf19R28

Thanks for the contribution!

**Comment by Ramshreyas** [comment]
Hi Artur,

Yes, the import line is correct!

Cheers,

Ram

**Comment by Svisstack** [comment]
@Ramshreyas Thanks for confirming. Have a nice week.
