### ISSUE TITLE
Golang data streaming API - Requesting volume data closes connection with error 1006

### ISSUE THREAD

**Issue by marvin-hansen** [coinapi/coinapi-sdk#110]
Issue related to PR #108  
 
Requesting data streams using Golang works for all message types except volume data. When constructing a hello message requesting only volume data, the connection terminates with error 1006. It is unclear to me why all other data types work as expected while requesting volume continues to throw that error. I am still investigation this error, but any help to fix this would be apricated. 

An isolated test replicating this issue is part of the PR. 
https://github.com/coinapi/coinapi-sdk/pull/108

**Comment by Svisstack** [comment]
@marvin-hansen Can you provide exact hello message that producing this behavior in json here?

**Comment by marvin-hansen** [comment]
@Svisstack  Thank you, 

I spent some time on the Sandy Console and eventually found the mistake. Essentially, for volume only the AssetID must be submitted but I was sending the SymbolID, which then caused the error. 

However, I think there should be a request validation in the API i.e. if volume gets requested using a hello message without AssetID, then return an error message and terminate then.  Would be nice to get such an error. 

However, I patch the code base and re-submit the PR. 

Thank you

**Comment by Svisstack** [comment]
We fixed that issue.
