### ISSUE TITLE
OEML Docker container hangs in crashloop

### ISSUE THREAD

**Issue by marvin-hansen** [coinapi/coinapi-sdk#112]
Trying to start the OEML docker container according to the manual, 
but no matter what I try, the container hangs in a crashloop.

On Windows (Powershell) 

Using the parameter, as documeted.
```
docker run -d --name=BINANCE --restart=always --net=host coinapi/oeml-api --OEML:ExchangeId BINANCE  --OD:PublicApiKey key_string  --OD:PrivateApiKey key string --CoinAPI:ApiKey key_string 
```

Using config file, as documented: 

```
docker run -d --name=BINANCE --restart=always --net=host coinapi/oeml-api --env-file oeml.env
```

oeml.env was created using:
```
cat > oeml.env << EOF

OEML__ExchangeId=BINANCE
CoinAPI__ApiKey=key_string

OD__PublicApiKey=key_string 
OD__PrivateApiKey=key_string 

EOF
```
key_string does not contain any whitespaces nor underscores. 

From the documentation, 
[Docker_Error_Log.txt](https://github.com/coinapi/coinapi-sdk/files/6781328/Docker_Error_Log.txt)
key / value pairs for env. variable must be:

* Strings
* Colons must be replaced by double underscore __ 
* Seperated by an equal sign

Which I translate to:

KEY__ID=VALUE 

However, the above format seems to trigger an exception when trying to parse the key/value string. 

When printing out the docker logs, I see the following exception :  

```
shutting down...
TODO - ThreadedSocketAcceptor.WaitForLogout not implemented!
[03:42:17 FTL] Host terminated unexpectedly
System.FormatException: Unrecognized Guid format.
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.Parse(String input)
   at CoinAPI.OEML.API.LicenseService.CreateApikeyUsageOEML() in /src/CoinAPI.OEML.API/LicenseService.cs:line 131
```

Practically speaking, how do I format the API keys to get the service up & running?

Thank you

**Comment by marvin-hansen** [comment]
Solved. Seems there was a copy error of the CoinAPI key.

Took me a some more tests to find out that Guid is the CoinAPI key.

**Comment by Svisstack** [comment]
Hi Marvin,

We will improve error reporting.

Thanks for the update.
