### ISSUE TITLE
Does this coinapi API support keep alive and HTTP 1.1

### ISSUE THREAD

**Issue by Antonhansel** [coinapi/coinapi-sdk#119]
Hello,

I was looking through the NodeJS SDK that we use and I realized that it doesnt use keep alive.
Is it an oversight ? Does this API support keep alive with HTTP 1.1 to do parallel requests ? 
Our infra is deployed on Azure and we are trying the reduce the number of outbound connections to prevent SNAT port exhaustions.

Thank you,

**Comment by Svisstack** [comment]
Hi @Antonhansel 

Yes of course we are using keep-alive from all versions of the protocol which we are implementing:

 * [HTTP1.0](https://datatracker.ietf.org/doc/html/rfc1945)
 * [HTTP1.1](https://datatracker.ietf.org/doc/html/rfc2616)
 * [HTTP2.0](https://datatracker.ietf.org/doc/html/rfc7540)

If your main concern is SNAT port exhaustion, then you can also consider using HTTP/2 which has multiplexing.

Let me know if you have further inquiries or questions.
