### ISSUE TITLE
Requesting multiple assets exchange rate

### ISSUE THREAD

**Issue by kafejo** [coinapi/coinapi-sdk#120]
Hi there, I'm trying to request multiple assets rates at the same time (documentation says coma or semicolon delimiter)

```python

    r = requests.get(production + "/v1/exchangerate/ETC;BTC", headers={"X-CoinAPI-Key": key})
```

But the response I get is empty:
```
{'asset_id_base': 'ETC;BTC', 'rates': []}
```

Any idea what I'm doing wrong?

**Comment by Svisstack** [comment]
asset_id_base does not support multiple assets[1]; you probably need to execute asset_id_base="USD" and filter_asset_id="ETH;BTC" with invert="true".

[1] https://docs.coinapi.io/#get-all-current-rates-get
