### ISSUE TITLE
OrderBookEvent

### ISSUE THREAD

**Issue by AlexITMS** [coinapi/coinapi-sdk#121]
Looking at the data passed into the event, all makes sense except for Asks and Bids, I can see they are type of object[] but I need to cast them to something more useful and because they seem to be a couple of levels deep and key value pairs I cannot seem to convert into something useful.

It's more my lack of understanding than anything else I am using C# personally I would have preferred the data was in 

`List<Asks> `

and 

`List<Bids>`

if that makes sense.

thank you

**Comment by Svisstack** [comment]
@AlexITMS Are you have the capacity to propose a PR for this change?

**Comment by Svisstack** [comment]
#123 fixed that
