### ISSUE TITLE
How to format URL to receive OHLCV 5 year time-series data returned in time ascending order on BTC  ?

### ISSUE THREAD

**Issue by lexypaul13** [coinapi/coinapi-sdk#122]
Hello Guys, how can I format this URL `//https://rest.coinapi.io/v1/ohlcv/ETH/history?period_id=5YRS&time_start=2016-01-01T00:00:00&apikey=03845084-94A5-40FA-92D1-AF0657EEBC52` to receive time series data on BTC ? This is the error  message I get "error": "Requested symbol_id is invalid does not exists."

**Comment by Svisstack** [comment]
Please change url to /v1/ohlcv/ETH/USD/history?...
