### ISSUE TITLE
Get detailed list of all symbols (Metadata) missmatching --- Metadata_list_symbolsAsync() / Symbol type

### ISSUE THREAD

**Issue by 3threeFX** [coinapi/coinapi-sdk#127]
Hi,
 I tried to fetch data with c# .net NuGet package 2.0.7 ... it's OK But there are a number of differences in real data (JSON) or [documents on the coinAPI](https://docs.coinapi.io/?csharp#list-all-symbols-get) site and your work exists Which confused me ...

CoinAPI developer documentation tells :

```
var client = new RestClient("https://rest.coinapi.io/v1/symbols");
var request = new RestRequest(Method.GET);
request.AddHeader("X-CoinAPI-Key", "73034021-THIS-IS-SAMPLE-KEY");
IRestResponse response = client.Execute(request);
    The above command returns JSON structured like this:
[
  {
    "symbol_id": "KRAKENFTS_PERP_BTC_USD",
    "exchange_id": "KRAKENFTS",
    "symbol_type": "PERPETUAL",
    "asset_id_base": "BTC",
    "asset_id_quote": "USD",
    "asset_id_unit": "USD",
    "future_contract_unit": 1.000000000,
    "future_contract_unit_asset": "USD",
    "data_start": "2019-10-30",
    "data_end": "2021-03-03",
    "data_quote_start": "2019-10-30T16:53:10.3262317Z",
    "data_quote_end": "2021-03-03T13:51:45.6970000Z",
    "data_orderbook_start": "2019-10-30T16:53:10.3262317Z",
    "data_orderbook_end": "2020-08-05T14:37:32.0080000Z",
    "data_trade_start": "2019-10-30T16:38:52.1620000Z",
    "data_trade_end": "2021-03-03T13:46:25.7810000Z",
    "volume_1hrs": 22897091.000000000,
    "volume_1hrs_usd": 22897091.00,
    "volume_1day": 459390289.000000000,
    "volume_1day_usd": 459390289.00,
    "volume_1mth": 12875674995.000000000,
    "volume_1mth_usd": 12875674995.00,
    "price": 51266,
    "symbol_id_exchange": "pi_xbtusd",
    "asset_id_base_exchange": "XBT",
    "asset_id_quote_exchange": "USD",
    "price_precision": 0.100000000,
    "size_precision": 1.000000000
  }, 

```
### First Issue:
but there is no date properties (in symbols class) for data start/end date in your implementation :

![Screenshot 2022-02-03 175454](https://user-images.githubusercontent.com/63404512/152362096-6320fdfa-c160-4d7b-8d88-c4c3f964ff75.png)

why are "data_start" , "data_end" , "data_quote_start" , "data_quote_end" , "data_orderbook_start" , "data_orderbook_end","data_trade_start","data_trade_end" ignored?

### Second Issue:
it's wired ... I try to view JSON stream with the browser it has an end date for some symbols but no start! (it seems necessary 
to have a start/end date to request ohlcv data? not ?) I really appreciate you guiding me through all of this! 
![Screenshot 2022-02-03 175951](https://user-images.githubusercontent.com/63404512/152362830-955b03e0-a6c1-4f3c-9f14-362ae4348be2.png)

![Screenshot 2022-02-03 182803](https://user-images.githubusercontent.com/63404512/152369042-0aba3156-6800-4be5-8fe2-87f5b75af4fd.png)

**Comment by Svisstack** [comment]
@3threeFX Please upgrade to 2.0.8, the missing fields are added. The second issue is related to the service, not the SDK itself. Can you push it to support@coinapi.io?
