### ISSUE TITLE
Do you have a working example for R

### ISSUE THREAD

**Issue by mubashirqasim** [coinapi/coinapi-sdk#13]
Hi there, 

Can you please share example R code to get historic data for a crypto?

Many thanks,

**Comment by AndrewManHayChiu** [comment]
@mubashirqasim 

Give the following a try:

`
## Initialise
library(httr)
library(jsonline)

## Setup GET request to coinapi
base <- "https://rest.coinapi.io/"
endpoint <- "/v1/exchangerate/BTC?apikey="  # note the request is for BTC
api_key <- "[your key]" 

## Create query string
call <- paste0(base, endpoint, api_key)

## Retrieve data via GET call
get_prices <- GET(call)

## Returns class "response"
class(get_prices)

## Process into a data table
get_prices_text <- content(get_prices, "text")  # Convert to "character"
get_prices_json <- fromJSON(get_prices_text, flatten = TRUE) # Flatten into list

## List contains two objects:
## 1 - asset_id_base
## 2 - rates
names(get_prices_json)

get_prices_json$asset_id_base

head(get_prices_json$rates)
`

**Comment by Svisstack** [comment]
I moved this response to the readme as the example of the usage of API form the R language. Thanks @AndrewManHayChiu for the effort

**Comment by Ramshreyas** [comment]
@Svisstack I've made an R package for the REST API: https://github.com/Ramshreyas/rcoinapi - please use and share as you see fit. Feedback welcome to improve it!
