### ISSUE TITLE
Question about CryptoTick

### ISSUE THREAD

**Issue by whyCPPgofast** [coinapi/coinapi-sdk#136]
Hey,

Sorry I had to reach out to you here but I need to talk to a dev before I consider buying data.

My question is regarding the collection of "trades" data.

Is the data collected live through a WS feed (with local timestamps) ?

I want to buy a dataset for FTX and Binance Futures but I need to know which AWS region the data was collected from (where is your data collecting bot hosted at)? Because of latency estimations.

Also are you using multiple connections for the same feed or just one connection?

**Comment by GabrielFernandezCoinAPI** [comment]
Hi there, this is Gabriel from the CoinAPI Support team. To answer your question, our trades data comes from WebSocket and we are using redundancy on a level higher than 3 independent server sites; most of our infrastructure is located in AWS in North America, Europe and Japan.
