### ISSUE TITLE
'Parameter subscribe_data_type is required.' error when value is set in message

### ISSUE THREAD

**Issue by murphman300** [coinapi/coinapi-sdk#150]
Hi,

Been trying to go through the authorization flow for a WebSocket setup, and have been getting this error (see title) despite specifying the relevant field explicitly - see bellow.

```

const handleSubscribe = () => {

    const  { COIN_LIST, WS_COIN_API_URL, COIN_API_KEY, WS_COIN_API_SUB_DATATYPES, WS_COIN_API_SUB_FILTER_ASSET_IDS } = process.env;

    const data = JSON.stringify({'message': {
        type: 'hello',
        apiKey: COIN_API_KEY,
        heartbeat: false,
        subscribe_data_type: ["trade"],
    }});

    console.log(data);

    ws.send(data)
}
```

This is the error I receive:

```
{
  message: 'Parameter subscribe_data_type is required.',
  type: 'error'
}
```

Is there a bug with the api, or is it possible my message object is not structured properly? The field is clearly in the object

Any guidance is appreciated

Cheers

**Comment by Jacob273** [comment]
Hello @murphman300 

It looks like the message is incorrectly constructed. Please try to use JSON.stringify on following object:

      const data = JSON.stringify(
            {"type":"hello",
            "apikey": COIN_API_KEY,
            "heartbeat": false,
            "subscribe_data_type": ["trade"]});
      }
