### ISSUE TITLE
Request for feedback on the python client

### ISSUE THREAD

**Issue by spacether** [coinapi/coinapi-sdk#155]
Hi there. I am the author of the openapi-generator python client which has now moved to https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
Your repo uses this client.
I want to make sure that I understand what is important to the end users of the python client. If you have some time can you provide some feedback on what features you value in the generator, any pain points, and what you would like improved?
If you could provide your feedback [here](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/179) it would help with future improvements. Thank you!

**Comment by GabrielFernandezCoinAPI** [comment]
Hi there, thank you for reaching out to us.
I am Gabriel from the CoinAPI Support Team. We appreciate your submitting this to us. I have forwarded your feedback request to our team to be looked at.
