### ISSUE TITLE
"Failed to verify API key privileges which are required to access this resource"

### ISSUE THREAD

**Issue by br4nnigan** [coinapi/coinapi-sdk#164]
so since yesterday getting rates fails, today I'm getting an e-mail that exciting changes are going to happen (or are happening...?). 

So I got a new free key and still in accordance with the documentation do this:

```
 curl -s https://rest.coinapi.io/v1/exchangerate/XMR/EUR \
 --request GET \
 --header "X-CoinAPI-Key: 018D3882-F8BA-4E50-8778-D46F1CA31F06"
```

which gives the above mentioned error: `Failed to verify API key privileges which are required to access this resource`

Why is that?

**Comment by CoinAPISupport** [comment]
Hi there,
 
We have been able to identify the problem causing this error and this should now be resolved. We apologize for the inconvenience this has caused. May I kindly ask if you are able to try again and see if it will now work for you? Please let us know if you encounter any issues.
 
Regards,
Gabriel Fernandez
CoinAPI Support

**Comment by br4nnigan** [comment]
Yes is has been resolved (yesterday already). Thanks.
