### ISSUE TITLE
No email is sent when requesting API key

### ISSUE THREAD

**Issue by valdoryu** [coinapi/coinapi-sdk#168]
Hi

I tried requesting a free api key through email input in the documentation & the form modal on the pricing page.
No email in my inboxes after two hours.
I tried many pro & personal emails but no luck.

Is your mailer down ?

**Comment by Jacob273** [comment]
Hi @valdoryu 

Please check your email, API key has been sent manually.

Indeed, for some addresses there was a problem with sending free API keys.
The issue is still ongoing and we will work on it.
