### ISSUE TITLE
[Request] Release a NuGet package for C#

### ISSUE THREAD

**Issue by mishra14** [coinapi/coinapi-sdk#23]
Can you please release a [NuGet package](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli) for the C# API?

It will make the api consumption easier. I am happy to help with a PR if needed.

**Comment by Svisstack** [comment]
Yes, that makes sense. Please feel free to help with the PR. I will handle CI flow that will publish to the Official NuGet repository.

**Comment by Svisstack** [comment]
We released the NuGet Package for the REST API and currently working on the WebSocket one which will be available next week.
