### ISSUE TITLE
Do you have a basic example for Elixir or Erlang? REST would be fine but Websockets better

### ISSUE THREAD

**Issue by vegabook** [coinapi/coinapi-sdk#24]
I have tried using HTTPoison, for example: 

```
iex(10)> HTTPoison.get "http://www.ibm.com"                                                    
{:ok,
 %HTTPoison.Response{
   body: "",
   headers: [
     {"Server", "AkamaiGHost"},
     {"Content-Length", "0"},
     {"Location", "https://www.ibm.com/"},
     {"Date", "Fri, 16 Mar 2018 23:15:37 GMT"},
     {"Connection", "keep-alive"},
     {"X-Content-Type-Options", "nosniff"},
     {"X-XSS-Protection", "1; mode=block"},
     {"Content-Security-Policy", "upgrade-insecure-requests"}
   ],
   request_url: "http://www.ibm.com",
   status_code: 301
 }}
```

No problemo. But:

```
iex(10)> HTTPoison.get "http://v1/exchangerate/BTC?apikey=MYAPIKEY"
{:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}

iex(11)> HTTPoison.get "/v1/exchangerate/BTC?apikey=MYAPIKEY"      
** (CaseClauseError) no case clause matching: []
    (hackney) /home/tbrowne/code/crypto/deps/hackney/src/hackney_url.erl:192: :hackney_url.parse_netloc/2
    (hackney) /home/tbrowne/code/crypto/deps/hackney/src/hackney.erl:331: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:439: HTTPoison.Base.request/9
```

Do you have something for Erlang or Elixir in the pipeline? I know for sure Erlang is used quite heavily in finance, and Elixir is gaining traction. Obviously I have changed MYAPIKEY to my real API key.

**Comment by Svisstack** [comment]
You should use "https://rest.coinapi.io/v1/exchangerate/BTC?apikey=MYAPIKEY" instead of 
 "http://v1/exchangerate/BTC?apikey=MYAPIKEY"

**Comment by Svisstack** [comment]
We are overloaded with the work and actually, Erlang or Elixir examples in SDK are not highly requested features, we hope that someone will PR these languages into the repo.

**Comment by vegabook** [comment]
"You are overloaded with work" is fine, but I am actually willing to pay on one of your premium services. So "we are overloaded with work" doesn't cut it. You are not open source. Let me remind you that multiple of your OWN sources have FREE APIs. Thank you.

**Comment by vegabook** [comment]
I have already noticed that on the free service, which is the starting point for most (willingly paying) potential customers, you guys are spotty at best. I'm not getting a good feeling here.

**Comment by Svisstack** [comment]
@vegabook Unfortunately implementing SDK in Erlang or Elixir is not on our roadmap for next 3 months. We are implementing custom features only for the Enterprise plan agreements.

**Comment by vegabook** [comment]
I will speak to your enterprise reps for costing analysis. Thank you for your response.
