### ISSUE TITLE
Fatal Error with use of GetTwitterLatest function

### ISSUE THREAD

**Issue by qnoox** [coinapi/coinapi-sdk#30]
Hello,

Any ideas why this happens?

**Error:**
PHP Fatal error:  Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /coinapi.inc.php:379
Stack trace:
#0 /coinapi.inc.php(379): Exception->__construct(Object(stdClass))
#1 /coinapi.inc.php(311): CoinAPI->CurlRequest('https://rest.co...')
#2 /getLatest.php(17): CoinAPI->GetTwitterLatest(200)
#3 {main}
  thrown in /coinapi.inc.php on line 379

**Code:**
require_once('coinapi.inc.php');

$api_key = "myAPIkeyHere";
$period_id = '1HRS';
$time_start = (new DateTime())->modify('-7 days');
$time_end = (new DateTime())->modify('-5 days');
$limit = 200;

$capi = new CoinAPI($api_key);

foreach($capi->GetTwitterLatest($limit) as $data) {

echo $data->id;
}

Thank you in advance.

**Comment by Svisstack** [comment]
Providing twitter related data via CoinAPI was discontinued permanently.

We adjusted the SDK to reflect that change.
