### ISSUE TITLE
COIN_API_SDK.ohlcv_historic_data() doesn't use time_end param

### ISSUE THREAD

**Issue by bfischer1121** [coinapi/coinapi-sdk#31]
"params.time" should be "params.time_end" at
https://github.com/coinapi/coinapi-sdk/blob/933bce956cad1aedefed5bc702c937dee3723b63/javascript-rest/coinapi_v1.js#L107

**Comment by Svisstack** [comment]
Thanks, was fixed in the #7e0476c
