### ISSUE TITLE
Java api BUG: binance and coinbase download different times (timezones?)

### ISSUE THREAD

**Issue by RobustCoder** [coinapi/coinapi-sdk#36]
I have Java code which uses the coinapi Java code to download market data every day.

In particular, I use its java_rest_coin_api class.

The relevant part of my download code that uses coinapi are these 2 lines:
```
java_rest_coin_api c = new java_rest_coin_api(KEY);
java_rest_coin_api.timedata[] result = c.ohlcv_get_historical_timeseries(symbol_id, period_id, time_start, time_end, limit);
```

The time_start arg that I supply is always the java.sql.Timestamp that represents the next interval start time AFTER the last interval that I previously downloaded the day before.

The time_end arg that I supply is always the Timestamp that represents 2222-01-01T00:00:00Z (i.e. a far distant future time).

This protocol should ensure that I download all the recent data that I am missing up to BUT NOT BEYOND the present.

When I ran my download at ~21:00 EDT (i.e. about 45 minutes ago), the download for 1 hour intervals for binance BTC/USDT behaved as expected.

In particular, the start time of the last interval downloaded was 2018-07-27T01:00:00Z.  That time is a UTC timezone value that corresponds to 21:00 EDT.  It is UTC because coinapi says that it always uses that timezone: "All time values we provide are UTC time zone. Do not assume otherwise."  See: [https://docs.coinapi.io/#time](https://docs.coinapi.io/#time)

**In contrast, when I immediately ran the same code to download coinbase BTC/USD data, it behaved incorrectly.**

_In particular, the start time of the last interval downloaded was 2018-07-27T05:00:00Z.  That date is 5 hours in the future, so it is obviously wrong!_

Does anyone know what is going on?

My guess: coinapi is incorrectly converting coinbase timestamps.  In particular, coinapi is assuming that the raw values it is getting from coinbase are in UTC−04:00 when in fact they are actually already in UTC.  So, coinapi is mistakenly adding 4 hours to them to convert them to what it thinks should be UTC.

If true, this indicates a serious bug in coinapi's internal code: they failed to write a DBC ("Design By Contract") check to insist that market data times can NEVER be in the future (barring small clock skew differences).

**Comment by RobustCoder** [comment]
I ran my market data download code several minutes ago, on 2018-07-29 at ~04:30:00 GMT.

This time, the downloads for both binance BTC/USDT as well as coinbase BTC/USD both had their final interval have the same start time of 2018-07-29T08:00:00Z.

_So, they are now both consistent, which is good._

**But they are both consistently wrong: both end with a time that is several hours into the future.**

Did you make an incomplete bug fix, coinapi?

**Comment by Svisstack** [comment]
@RobustCoder We are handling timestamps correctly and also correctly distribute data via the API, if there is a bug it needs to be inside Java code with the timezone handling (not assuming UTC and converting your local time to the UTC which is creating offset).

This could be the case?

**Comment by RobustCoder** [comment]
Artur,

Thanks for getting back to me.

*I spent time debugging this just now, and now and I now know exactly what
is going on.*

*The essence of the BUG is that your java_rest_coin_api is using your local
time zone instead of UTC because it uses that bad old java.sql.TimeStamp
class.*

Its precise_time_to_string method:
--is used to send times to your website json API
--it takes in a TimeStamp instance--which represents an absolute moment in
time--but it wrongly uses that class's date field methods to construct the
time String that gets sent
--the problem is that TimeStamp's date field methods use your local time
zone, not UTC!

Its precise_time_from_string method:
--is used to parse times received from your website json API
--it parses the date fields from the String received
--then it wrongly uses those fields to construct a TimeStamp instance
--again, the problem is that TimeStamp's date field methods assume your
local time zone, not UTC!
--so the TimeStamp instance now has wrongly parsed the absolute time

Attached is a Java class JavaApiTimezoneBug which proves all these points.

At the end of this email is the console output that it produces.

Note: this output is valid for me in the EDT time zone, if you are in
another time zone, you will get different results.  In particular, if you
are in the UTC time zone, like London, you actually will be blind to the
BUG!  That could be why your developer missed it...

*Concerning fixes, I will respond to another of your emails, stay tuned.*

Regards,

Brent Boyer


--------------------------------------------------
timeSentIsWrong
--------------------------------------------------

t_coinapi:
2018-07-30T10:02:44

t_Instant:
2018-07-30T10:02:44Z
you should see that this perfectly reproduces t_coinapi followed by the
explicit time zone for UTC

t_Timestamp:
2018-07-30 06:02:44.0
you should see that Timestamp has converted the time into your local time
zone, this is dangerous!

t_apiString:
2018-07-30T06:02:44
HERE IS THE BUG: java_rest_coin_api.precise_time_to_string sends that
Timestamp as the local time zone String--it failed to convert it to UTC

--------------------------------------------------
timeReceivedIsWrong
--------------------------------------------------

t_coinapi:
2018-07-30T10:02:44

t_Instant.toEpochMilli():
1532944964000

t_apiTimestamp.getTime():
1532959364000

t_apiTimestamp.getTime() - t_Instant.toEpochMilli():
14400000
You should see that t_Instant and t_apiTimestamp represent different
absolute moments in time (units here: number of millseconds since the
epoch).
REASON FOR THE BUG: java_rest_coin_api.precise_time_from_string parsed
t_coinapi into a Timestamp with date fields that assume the local time zone
String--it failed to recognize that its fields are for UTC

**Comment by RobustCoder** [comment]
p.s. I forgot to mention: to get my attached class JavaApiTimezoneBug to
run, you need to modify the access privilege of those 2 methods in
java_rest_coin_api.java.

In particular, remove the "private" modifier from the definition of the
precise_time_to_string and precise_time_from_string methods.

**Comment by RobustCoder** [comment]
This bug was fixed in the in the [recent refactoring of coinapi's Java SDK](https://github.com/coinapi/coinapi-sdk/tree/master/java-rest-v2).
