### ISSUE TITLE
Java API questionable choice of Timestamp instead of Instant

### ISSUE THREAD

**Issue by RobustCoder** [coinapi/coinapi-sdk#39]
The sole Java API class java_rest_coin_api uses an old class, java.sql.Timestamp, to represent all time instances.

That is a strange choice: this API does no interaction with databases at all, so why use a class from java.sql?

Java 8 introduced a new time API that blows away the old Java classes in every way I know of.  If you are unfamiliar, check out [this introduction.](https://www.journaldev.com/2800/java-8-date-localdate-localdatetime-instant).

In java_rest_coin_api, I think that every current use of Timestamp should be replaced by the new Java time API class Instant.

**Comment by Svisstack** [comment]
I'm actually don't know the logic behind it as we did not maintain contact with the developer which wrote the JAVA SDK, however main question is: this create any issue? is this could be related to your previous issue with the timezone?

**Comment by carwilki** [comment]
java.sql.Timstamp is intended for use with jdbc stuff and is really not something that should be used...really ever at least out side of jdbc. since there are already other libraries required to use this then i would think that you can at least use Joda Time or if you only support jdk 1.8+  then you should be using the JSR-310 java.time implementation.

**Comment by RobustCoder** [comment]
carwilki: you are correct.

In the [recent refactoring of coinapi's Java SDK](https://github.com/coinapi/coinapi-sdk/tree/master/java-rest-v2), java.sql.Timstamp was totally replaced by java.time.Instant.

That change not only fixed the time zone bug reported in [https://github.com/coinapi/coinapi-sdk/issues/36](https://github.com/coinapi/coinapi-sdk/issues/36), it also simplified the code.

That refactoring addressed a bunch of other issues too.  Check it out!
