### ISSUE TITLE
name and id are reversed for IOTA?

### ISSUE THREAD

**Issue by RobustCoder** [coinapi/coinapi-sdk#40]
I downloaded all the assets available on coinapi just now using this URL: [https://rest.coinapi.io/v1/assets](https://rest.coinapi.io/v1/assets).

Here is the raw JSON for IOTA (MIOTA):

```
{
	"asset_id": "IOTA",
	"name": "MIOTA",
	"type_is_crypto": 1,
	"data_start": "2017-06-13",
	"data_end": "2018-08-23",
	"data_quote_start": "2017-06-13T16:51:17.1775282Z",
	"data_quote_end": "2018-08-23T21:03:51.0029903Z",
	"data_orderbook_start": "2017-06-13T16:51:17.1775282Z",
	"data_orderbook_end": "2018-08-23T21:03:51.0029903Z",
	"data_trade_start": "2017-06-13T16:51:20.0000000Z",
	"data_trade_end": "2018-08-23T21:05:37.0000000Z",
	"data_trade_count": 27072757,
	"data_symbols_count": 25
},
```

Note that coinapi is claiming that the asset_id (i.e. symbol) is IOTA while the name is MIOTA.

I think that that is reversed!

For example, checkout this page: [https://coinmarketcap.com/currencies/iota/](https://coinmarketcap.com/currencies/iota/).  Note how it puts MIOTA in parentheses, which is what coinmarketcap does for ids, not names.

Of all the assets that  downloaded from coinapi, I checked the top 10 crypto currencies by market cap, and only IOTA has this error.

**Comment by Svisstack** [comment]
We didn't consider that as an error as we did maintain own asset database. Some exchanges incorporated IOTA and some MIOTA, more of them used IOTA and we decided to follow that, we will not change it as it could break some behavior on the client side for existing customers.
