### ISSUE TITLE
Get orderbooks current data by multiple symbols

### ISSUE THREAD

**Issue by bfischer1121** [coinapi/coinapi-sdk#42]
Hi it would be nice if
https://github.com/coinapi/coinapi-sdk/blob/56aca0bcce3612194da845da771f52fd5298d883/javascript-rest/coinapi_v1.js#L220

was something like
```javascript
var path = this.url + ("/v1/orderbooks/current?filter_symbol_id=" + symbol_id);
```
to allow filtering by multiple symbols

**Comment by Svisstack** [comment]
@bfischer1121 It's already like that.

eg. http://rest.coinapi.io/v1/orderbooks/current?apikey=XXX&filter_symbol_id=BITSTAMP_SPOT_BTC_USD;BITSTAMP_SPOT_ETH_USD

It's also documented in the: https://docs.coinapi.io/#current-data32

**Comment by bfischer1121** [comment]
@Svisstack Yea the API allows it but I'm referring to the SDK method referenced above. It uses the 1st variant that throws errors if you try comma or semi-colon delimited filters. I'm making a custom request instead of using the SDK in this instance, but it would be nice to use the SDK as it has `transformResponse`

**Comment by Svisstack** [comment]
@bfischer1121 This will fix your issue? https://github.com/coinapi/coinapi-sdk/pull/43

**Comment by bfischer1121** [comment]
Yea looks great - thank you

**Comment by Svisstack** [comment]
It's merged.
