### ISSUE TITLE
C# Library

### ISSUE THREAD

**Issue by GravlLift** [coinapi/coinapi-sdk#46]
Is there a reason that the c# version is released as a console application instead of a class library? Presumably anyone who wants to use it is going to have to customize it into a class library and make the class "CoinApi" public if that actually want to use it.

**Comment by Svisstack** [comment]
@GravlLift We converted the C# version into the class library and released it on the NuGet. We are currently working on the WebSocket SDK which will also be available on the NuGet and in the repository next week.
