### ISSUE TITLE
New SendHelloMessage doesn't seem to update symbol subscriptions

### ISSUE THREAD

**Issue by graham83** [coinapi/coinapi-sdk#61]
I have implemented the CoinAPI SDK websocket client for C# - having some issues with subsequent SendHello messages to update the subscribed trade update symbols. 

The initial SendHelloMessage works and i receive updates for any symbols contained in subscribe_filter_symbol_id.  But if I try to update my subscriptions with new symbols via a subsequent SendHello it seems to be ignored and I continue receiving trade updates for the original subscribe_filter_symbol_id list.

**Comment by Svisstack** [comment]
Thanks for observing that issue. It's fixed in the 1.6.0, currently newest version in the NuGet.
