### ISSUE TITLE
Testing Code in library?

### ISSUE THREAD

**Issue by Shidzy2** [coinapi/coinapi-sdk#69]
https://github.com/coinapi/coinapi-sdk/blob/dev/data-api/csharp-rest/CoinAPI.REST.V1/CoinApiRestClient.cs
in "private T GetData<T>(string url)" :
![image](https://user-images.githubusercontent.com/45227075/89997792-4ee3a100-dc95-11ea-8637-2c34182171a2.png)

is this some testing code in library? and its pushed to nuget?

**Comment by Svisstack** [comment]
@Shidzy2 Fixed in 2.0.0

3a80541e31ad0c59e5fdc5d39cca4d0dcabb5f9c
