### ISSUE TITLE
Why all requests are sync?

### ISSUE THREAD

**Issue by Shidzy2** [coinapi/coinapi-sdk#70]
https://github.com/coinapi/coinapi-sdk/blob/dev/data-api/csharp-rest/CoinAPI.REST.V1/CoinApiRestClient.cs
Why all requests are sync? while in GetData<T> you use GetAsync but take result from it, please use async/await because its impossible to use this nuget like this

![image](https://user-images.githubusercontent.com/45227075/89998068-b7328280-dc95-11ea-9796-c834b1960d19.png)

**Comment by Svisstack** [comment]
@Shidzy2 Fixed in 2.0.0

3a80541e31ad0c59e5fdc5d39cca4d0dcabb5f9c
