### ISSUE TITLE
Can't import in Python (ImportError: cannot import name 'CoinAPIv1')

### ISSUE THREAD

**Issue by olalonde** [coinapi/coinapi-sdk#86]
`ImportError: cannot import name 'CoinAPIv1'`

<img width="1171" alt="Screen Shot 2021-01-20 at 5 22 38 PM" src="https://user-images.githubusercontent.com/416585/105241509-27e2a280-5b44-11eb-92f2-30e51cc1e656.png">

**Comment by tprzybysz** [comment]
Please update lib (coinapi.rest.v1 1.3)
`pip install --upgrade coinapi_rest_v1`

import this way
`from coinapi_rest_v1.restapi import CoinAPIv1`
