### ISSUE TITLE
Cannot import CoinAPIv1 with Python

### ISSUE THREAD

**Issue by tionebrr** [coinapi/coinapi-sdk#93]
Hello folks,

Here is my commands list
```shell
cd <project>
virtualenv <project_env>
source ./<project_env>/bin/activate
pip3 install coinapi.rest.v1 # no issue here
git clone https://github.com/coinapi/coinapi-sdk/data-api/python-rest/coinapi_rest_v1
cd <coinapi-sdk/data/python/coinapi_rest_v1>
python example.py <API_KEY>
```
Which results in
```shell 
Traceback (most recent call last): 
  File "examples.py", line 1, in <module>
    from coinapi_rest_v1 import CoinAPIv1
ImportError: cannot import name 'CoinAPIv1' from 'coinapi_rest_v1' (/home/user/Development/project/project_env/lib/python3.8
```

Tested on Arch (python 3.8.6) and Windows (python 3.9.0).

**Comment by Svisstack** [comment]
Hi @tionebrr 

Please try to run the examples directly from the source as the package is probably directly referenced in the examples file.

https://github.com/coinapi/coinapi-sdk/blob/master/data-api/python-rest/README.md

**Comment by tionebrr** [comment]
Hi ! Thanks for the prompt answer !

What you're suggesting is what I'm trying actually (unless I'm missing something?). I'm here:
```shell 
$ pwd 
/home/btrr/Development/pythonTrading/coinapi-sdk/data-api/python-rest/coinapi_rest_v1 
$ python examples.py
Traceback (most recent call last): 
  File "examples.py", line 1, in <module> 
    from coinapi_rest_v1 import CoinAPIv1 
ModuleNotFoundError: No module named 'coinapi_rest_v1' 
```

I see the `python-rest` folder is in the `data-api` subfolder which does not appear in the documentation. Could that be an issue?

**Comment by tionebrr** [comment]
Found a workaround here: https://github.com/coinapi/coinapi-sdk/issues/86
