### ISSUE TITLE
c# Websocket SDK - Use ConcurrentQueue instead of Queue and Remove Lock for faster receiving of Data

### ISSUE THREAD

**Issue by firephantomassasin** [coinapi/coinapi-sdk#96]
Hi,

I would like to suggest to use concurrentQueue instead of Queue and remove the lock for faster receiving of data and this will prevent from timing out or disconnecting from the Websocket Server.

ConcurrentQueue is thread-safe and you can have multiple threads doing enqueue and dequeue at the same time, giving it more better performance rather than using 1 lock for enqueue and dequeue.

**Comment by Svisstack** [comment]
This is more complicated as the ConcurrentQueue has a memory leak that will not be fixed, so we avoid it as much as possible, but there are other viable resolutions to this problem, however, this should be properly benchmarked.

**Comment by firephantomassasin** [comment]
@Svisstack  i saw that issue, however i'm not sure if it is still happening on newer .net framework (like .net framework > 4.7.2 or 4.8 or .net 5).

There is still article: https://devblogs.microsoft.com/pfxteam/concurrentqueuet-holding-on-to-a-few-dequeued-elements/

**Comment by Svisstack** [comment]
The leak still exists in .NET 5.0. Its presence is highly dependent on how you actually use the collection and on the number of elements, but it's a too big problem to let roll the dice.

**Comment by firephantomassasin** [comment]
Alright Thanks @Svisstack for your insights.
