### ISSUE TITLE
c# websocket Sdk - utf8json library has some bugs and issues

### ISSUE THREAD

**Issue by firephantomassasin** [coinapi/coinapi-sdk#98]
Hi we have just found out that the c# websocket sdk is referencing the https://github.com/neuecc/Utf8Json/issues library, upon checking the latest version of this library contains a lot of issues and bugs, did you guys make a forked version of this or do you just use the latest version from the original repo?

**Comment by Svisstack** [comment]
Hi @firephantomassasin,

We are using the latest public version and have 100% test coverage on our side in terms of handing the DTO structures, including allocation tests. 

Please provide at least one example when it behaving incorrectly in this specific case and we could process that further.

**Comment by firephantomassasin** [comment]
Hi, you could check this one: https://github.com/neuecc/Utf8Json/issues/154

**Comment by Svisstack** [comment]
It needs to be a real problem with the SDK library, both of the issues are irrelevant here.

Please create a separate case when for each issue with the SDK library.
